# TF IDF

In [20]:
import pandas as pd
data = pd.read_csv("training2.csv")
data.head()
arr = data.to_numpy()
arr2 = [] 
for i in range(len(arr)):
    arr2.append(arr[i])

arr2

[array(["is upset that he can't update his Facebook by texting it... and might cry as a result  School today also. Blah!"],
       dtype=object),
 array(['@Kenichan I dived many times for the ball. Managed to save 50%  The rest go out of bounds'],
       dtype=object),
 array(['my whole body feels itchy and like its on fire '], dtype=object),
 array(["@nationwideclass no, it's not behaving at all. i'm mad. why am i here? because I can't see you all over there. "],
       dtype=object),
 array(['@Kwesidei not the whole crew '], dtype=object),
 array(['Need a hug '], dtype=object),
 array(["@LOLTrish hey  long time no see! Yes.. Rains a bit ,only a bit  LOL , I'm fine thanks , how's you ?"],
       dtype=object),
 array(["@Tatiana_K nope they didn't have it "], dtype=object),
 array(['@twittera que me muera ? '], dtype=object),
 array(["spring break in plain city... it's snowing "], dtype=object),
 array(['I just re-pierced my ears '], dtype=object),
 array(["@caregiving I couldn't bear 

In [21]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer()

In [22]:
vec.fit(arr)
print(vec.idf_)

AttributeError: 'numpy.ndarray' object has no attribute 'lower'

SVD
BREAK A MATRIX INTO U. Sigma. V^T

In [23]:
# SVD USE : The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for reducing a matrix to its constituent parts to make certain subsequent matrix calculations simpler.
# The function takes a matrix and returns the U, Sigma, and V^T elements. The Sigma diagonal matrix is returned as a vector of singular values. The V matrix is returned in a transposed form, e.g. V.T.

In [24]:
import numpy as np
from scipy.linalg import svd

def calcMat_AAt(M):
    newM = np.dot(M,M.T)
    eigenvalues,eigenvectors = np.linalg.eig(newM)
    ncols = np.argsort(eigenvalues)[::-1]
    return eigenvectors[:,ncols]

def calcMat_AtA(M):
    newM = np.dot(M.T,M)
    eigenvalues,eigenvectors = np.linalg.eig(newM)
    ncols = np.argsort(eigenvalues)[::-1]
    return eigenvectors[:,ncols].T

def calcD(M):
    if(np.size(np.dot(M,M.T)))>(np.size(np.dot(M.T,M))):
        newM = np.dot(M.T,M)
    else :
        newM = np.dot(M,M.T)

    eigenvalues, eigenvectors = np.linalg.eig(newM)
    eigenvalues = np.sqrt(eigenvalues)
    return eigenvalues[::-1]

In [25]:
A = np.array([[4, 2, 0], [1, 5, 6]])

Vt = calcMat_AtA(A)
U = calcMat_AAt(A)
sigma = calcD(A)
print(Vt,"\n")
print(U,"\n")
print(sigma)
U_svd, D, VT = np.linalg.svd(A)
print(VT, "\n")
print(U_svd, "\n")
print(D)

[[-0.26001965 -0.65919758 -0.70558368]
 [-0.89132415 -0.11719389  0.43795758]
 [ 0.37139068 -0.74278135  0.55708601]] 

[[-0.28978415 -0.95709203]
 [-0.95709203  0.28978415]] 

[8.13872588 3.97003036]
[[ 0.26001965  0.65919758  0.70558368]
 [ 0.89132415  0.11719389 -0.43795758]
 [ 0.37139068 -0.74278135  0.55708601]] 

[[ 0.28978415  0.95709203]
 [ 0.95709203 -0.28978415]] 

[8.13872588 3.97003036]
